# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7020c731d2beac5dcc37d12754ba9410751b2b4c644fc2d730c2e5a9e3908d900fdb6300f166575f1203983b3e00a9f0e5b06670181e073a14e6b5651bb892

test:
  secret_key_base: b8c6277d217830f3ac71e843705df8404248bda4909655846bbd2d1874551a4348f21c34a7fa1af00cb57bfa994f0a23eb71ad63c2ad4759857bc39ab453147d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
